export const seedPatients = [
  {
    id: "PAT-2026-1001",
    name: "Aarav Sharma",
    age: 34,
    gender: "Male",
    phone: "9876543210",
    bloodGroup: "O+",
    address: "12 Park Street, Kolkata",
    lastVisit: "2026-08-25",
    allergies: ["Seasonal pollen"],
    existingConditions: ["Migraine"],
    currentMedications: ["Sumatriptan as needed"],
    emergencyContact: "Meera Sharma · 9876500011",
    status: "Active",
  },
  {
    id: "PAT-2026-1002",
    name: "Ananya Iyer",
    age: 28,
    gender: "Female",
    phone: "9823456710",
    bloodGroup: "B+",
    address: "Indiranagar, Bengaluru",
    lastVisit: "2026-08-22",
    allergies: [],
    existingConditions: ["Hypothyroidism"],
    currentMedications: ["Levothyroxine 50 mcg"],
    emergencyContact: "Raj Iyer · 9823400012",
    status: "Active",
  },
  {
    id: "PAT-2026-1003",
    name: "Rohan Verma",
    age: 45,
    gender: "Male",
    phone: "9811122233",
    bloodGroup: "A+",
    address: "Vaishali Nagar, Jaipur",
    lastVisit: "2026-08-18",
    allergies: ["Penicillin"],
    existingConditions: ["Hypertension"],
    currentMedications: ["Amlodipine 5 mg"],
    emergencyContact: "Kavita Verma · 9811100013",
    status: "Active",
  },
  {
    id: "PAT-2026-1004",
    name: "Priya Nair",
    age: 39,
    gender: "Female",
    phone: "9898981234",
    bloodGroup: "AB+",
    address: "Kakkanad, Kochi",
    lastVisit: "2026-08-12",
    allergies: ["Shellfish"],
    existingConditions: ["Type 2 Diabetes"],
    currentMedications: ["Metformin 500 mg"],
    emergencyContact: "Arun Nair · 9898900014",
    status: "Active",
  },
  {
    id: "PAT-2026-1005",
    name: "Vikram Singh",
    age: 52,
    gender: "Male",
    phone: "9765432109",
    bloodGroup: "B-",
    address: "Sector 62, Noida",
    lastVisit: "2026-08-05",
    allergies: [],
    existingConditions: ["High cholesterol"],
    currentMedications: ["Rosuvastatin 10 mg"],
    emergencyContact: "Neha Singh · 9765400015",
    status: "Active",
  },
  {
    id: "PAT-2026-1006",
    name: "Kavya Reddy",
    age: 24,
    gender: "Female",
    phone: "9900112233",
    bloodGroup: "O-",
    address: "Banjara Hills, Hyderabad",
    lastVisit: "2026-07-29",
    allergies: ["Ibuprofen"],
    existingConditions: [],
    currentMedications: [],
    emergencyContact: "Suresh Reddy · 9900100016",
    status: "Active",
  },
  {
    id: "PAT-2026-1007",
    name: "Sanjay Patel",
    age: 61,
    gender: "Male",
    phone: "9988776655",
    bloodGroup: "A-",
    address: "Vastrapur, Ahmedabad",
    lastVisit: "2026-07-21",
    allergies: [],
    existingConditions: ["Arthritis"],
    currentMedications: ["Calcium supplement"],
    emergencyContact: "Bhavna Patel · 9988700017",
    status: "Active",
  },
  {
    id: "PAT-2026-1008",
    name: "Meera Joshi",
    age: 31,
    gender: "Female",
    phone: "9871204567",
    bloodGroup: "B+",
    address: "Kothrud, Pune",
    lastVisit: "2026-07-14",
    allergies: [],
    existingConditions: ["PCOS"],
    currentMedications: [],
    emergencyContact: "Akash Joshi · 9871200018",
    status: "Active",
  },
  {
    id: "PAT-2026-1009",
    name: "Arjun Das",
    age: 48,
    gender: "Male",
    phone: "9830012345",
    bloodGroup: "O+",
    address: "Salt Lake, Kolkata",
    lastVisit: "2026-07-06",
    allergies: ["Dust"],
    existingConditions: ["Asthma"],
    currentMedications: ["Salbutamol inhaler"],
    emergencyContact: "Rita Das · 9830000019",
    status: "Active",
  },
  {
    id: "PAT-2026-1010",
    name: "Ishita Kapoor",
    age: 36,
    gender: "Female",
    phone: "9912345678",
    bloodGroup: "AB-",
    address: "Civil Lines, Delhi",
    lastVisit: "2026-06-28",
    allergies: [],
    existingConditions: [],
    currentMedications: [],
    emergencyContact: "Rohit Kapoor · 9912300020",
    status: "Active",
  },
];

export const seedConsultations = [
  {
    id: "CON-001",
    patientId: "PAT-2026-1001",
    date: "2026-08-25",
    chiefComplaint: "Fever and severe headache since two days",
    symptoms: ["Fever", "Headache", "Body ache", "Chills"],
    vitals: {
      temperature: "101.4",
      bloodPressure: "120/80",
      pulse: "92",
      spo2: "98",
      weight: "72",
      height: "174",
      bmi: "23.8",
    },
    diagnosis: "Viral Fever",
    doctorNotes: "Clinical examination reassuring. No signs of bacterial infection. Encouraged hydration and rest.",
    followUpInstructions: "Return if fever persists beyond 3 days.",
    prescriptionId: "RX-001",
  },
  {
    id: "CON-002",
    patientId: "PAT-2026-1001",
    date: "2026-07-10",
    chiefComplaint: "Recurring migraine attack with visual aura",
    symptoms: ["Migraine", "Photophobia", "Nausea"],
    vitals: {
      bloodPressure: "118/76",
      pulse: "76",
      spo2: "99",
    },
    diagnosis: "Migraine with aura",
    doctorNotes: "Discussed trigger avoidance. Prescribed sumatriptan for acute attacks.",
    followUpInstructions: "Maintain a migraine diary.",
    prescriptionId: "RX-002",
  },
  {
    id: "CON-003",
    patientId: "PAT-2026-1002",
    date: "2026-08-22",
    chiefComplaint: "Fatigue, weight gain, and cold intolerance",
    symptoms: ["Fatigue", "Weight gain", "Cold intolerance"],
    vitals: {
      bloodPressure: "110/70",
      pulse: "64",
      spo2: "99",
      weight: "58",
      height: "162",
      bmi: "22.1",
    },
    diagnosis: "Hypothyroidism follow-up",
    doctorNotes: "Continue Levothyroxine 50mcg. Thyroid panel due in 8 weeks.",
    followUpInstructions: "Repeat TSH after 8 weeks.",
    prescriptionId: "RX-003",
  },
  {
    id: "CON-004",
    patientId: "PAT-2026-1003",
    date: "2026-08-18",
    chiefComplaint: "Elevated home blood pressure readings (>140/90)",
    symptoms: ["Mild dizziness", "Occasional headache"],
    vitals: {
      bloodPressure: "148/92",
      pulse: "78",
      spo2: "98",
      weight: "84",
      height: "176",
      bmi: "27.1",
    },
    diagnosis: "Essential hypertension",
    doctorNotes: "Adherence counselling given. Low sodium diet advised.",
    followUpInstructions: "Monitor BP twice weekly at home. Review in 4 weeks.",
    prescriptionId: "RX-005",
  },
];

export const seedPrescriptions = [
  {
    id: "RX-001",
    patientId: "PAT-2026-1001",
    consultationId: "CON-001",
    date: "2026-08-25",
    diagnosis: ["Viral Fever"],
    doctorName: "Dr. Sudip Mukherjee",
    medicines: [
      {
        id: "MED-RX-01",
        medicineName: "Paracetamol 650mg",
        dosage: "1 tablet",
        frequency: "Three times daily",
        duration: "3 days",
        foodInstruction: "After food",
        instructions: "Take when fever or pain is present.",
      },
      {
        id: "MED-RX-02",
        medicineName: "Pantoprazole 40mg",
        dosage: "1 tablet",
        frequency: "Once daily",
        duration: "5 days",
        foodInstruction: "Empty stomach",
        instructions: "Take 30 minutes before breakfast.",
      },
      {
        id: "MED-RX-03",
        medicineName: "ORS (Oral Rehydration Salts)",
        dosage: "1 sachet",
        frequency: "Three times daily",
        duration: "3 days",
        foodInstruction: "Any time",
        instructions: "Dissolve in 1 litre water.",
      },
    ],
    generalInstructions: "Complete bed rest for 3 days. Plenty of warm fluids.",
    followUpInstructions: "Review after 3 days if fever does not settle.",
  },
  {
    id: "RX-002",
    patientId: "PAT-2026-1001",
    consultationId: "CON-002",
    date: "2026-07-10",
    diagnosis: ["Migraine with aura"],
    doctorName: "Dr. Sudip Mukherjee",
    medicines: [
      {
        id: "MED-RX-04",
        medicineName: "Sumatriptan 50mg",
        dosage: "1 tablet",
        frequency: "As needed",
        duration: "As required",
        foodInstruction: "Any time",
        instructions: "Take at first onset of aura.",
      },
    ],
    generalInstructions: "Avoid screen time during attacks.",
    followUpInstructions: "Maintain headache diary.",
  },
  {
    id: "RX-003",
    patientId: "PAT-2026-1002",
    consultationId: "CON-003",
    date: "2026-08-22",
    diagnosis: ["Hypothyroidism follow-up"],
    doctorName: "Dr. Sudip Mukherjee",
    medicines: [
      {
        id: "MED-RX-06",
        medicineName: "Levothyroxine 50 mcg",
        dosage: "1 tablet",
        frequency: "Once daily",
        duration: "30 days",
        foodInstruction: "Empty stomach",
        instructions: "Take early morning 30 min before breakfast.",
      },
    ],
    generalInstructions: "Do not skip morning dose.",
    followUpInstructions: "Repeat TSH after 8 weeks.",
  },
];

export const seedBills = [
  {
    id: "BILL-001",
    patientId: "PAT-2026-1001",
    date: "2026-08-25",
    description: "Consultation fee",
    amount: 600,
    paymentMethod: "UPI",
    status: "Paid",
    paidAmount: 600,
  },
  {
    id: "BILL-002",
    patientId: "PAT-2026-1001",
    date: "2026-08-25",
    description: "Lab tests",
    amount: 850,
    paymentMethod: "Cash",
    status: "Partial",
    paidAmount: 500,
  },
  {
    id: "BILL-003",
    patientId: "PAT-2026-1002",
    date: "2026-08-22",
    description: "Consultation fee",
    amount: 600,
    paymentMethod: "Card",
    status: "Paid",
    paidAmount: 600,
  },
  {
    id: "BILL-004",
    patientId: "PAT-2026-1003",
    date: "2026-08-18",
    description: "Consultation fee",
    amount: 600,
    paymentMethod: "Cash",
    status: "Pending",
    paidAmount: 0,
  },
];
